//! FSRS-5 scheduler.
//!
//! Tracks per-card memory **stability** (days until retrievability falls to the
//! desired retention) and **difficulty** ([1,10]). The next interval is the
//! stability scaled so predicted retrievability equals the deck's desired
//! retention. Weights are the published FSRS-5 defaults (per-deck overridable);
//! the optimiser that fits weights from review history is a later milestone.
//!
//! This is a faithful implementation of the FSRS-5 formulas. It is validated by
//! property tests (monotonicity, bounds, growth); parity against Anki's own
//! FSRS output is a follow-up that needs reference vectors generated by Anki.

use synapse_core::scheduling::{
    AnswerOutcome, CardPhase, CardState, Interval, SchedConfig, SchedContext, Scheduler,
};
use synapse_core::{Algorithm, Rating};

const DECAY: f64 = -0.5;
/// FACTOR = 0.9^(1/DECAY) − 1 = 19/81.
const FACTOR: f64 = 19.0 / 81.0;

#[derive(Debug, Default, Clone, Copy)]
pub struct FsrsScheduler;

impl Scheduler for FsrsScheduler {
    fn algorithm(&self) -> Algorithm {
        Algorithm::Fsrs
    }

    fn answer(&self, state: &CardState, rating: Rating, ctx: &SchedContext) -> AnswerOutcome {
        let cfg = &ctx.config;
        let w = &cfg.fsrs_weights;
        let g = rating as i64; // 1..=4

        let (stability, difficulty, lapse) = match (state.stability, state.difficulty) {
            (Some(s), Some(d)) => {
                let elapsed =
                    (ctx.today - state.last_review_day.unwrap_or(ctx.today)).max(0) as f64;
                let r = retrievability(elapsed, s);
                let difficulty = next_difficulty(w, d, g);
                let stability = if g == 1 {
                    forget_stability(w, d, s, r)
                } else {
                    success_stability(w, d, s, r, g)
                };
                (stability, difficulty, g == 1)
            }
            // First review: initial stability/difficulty from the rating.
            _ => (initial_stability(w, g), initial_difficulty(w, g), false),
        };

        let days = interval_from_stability(stability, cfg);
        AnswerOutcome {
            next: CardState {
                phase: CardPhase::Review,
                interval_days: days,
                reps: state.reps + 1,
                lapses: state.lapses + lapse as u32,
                stability: Some(stability),
                difficulty: Some(difficulty),
                last_review_day: Some(ctx.today),
                ..*state
            },
            interval: Interval::Days(days),
        }
    }
}

fn initial_stability(w: &[f64; 19], g: i64) -> f64 {
    w[(g - 1) as usize].max(0.1)
}

fn initial_difficulty(w: &[f64; 19], g: i64) -> f64 {
    (w[4] - (w[5] * (g - 1) as f64).exp() + 1.0).clamp(1.0, 10.0)
}

/// Difficulty at the "easy" anchor, used for mean reversion.
fn difficulty_easy_anchor(w: &[f64; 19]) -> f64 {
    initial_difficulty(w, 4)
}

fn next_difficulty(w: &[f64; 19], d: f64, g: i64) -> f64 {
    let delta = -w[6] * (g - 3) as f64;
    let damped = d + delta * (10.0 - d) / 9.0;
    (w[7] * difficulty_easy_anchor(w) + (1.0 - w[7]) * damped).clamp(1.0, 10.0)
}

fn retrievability(elapsed_days: f64, stability: f64) -> f64 {
    (1.0 + FACTOR * elapsed_days / stability).powf(DECAY)
}

fn success_stability(w: &[f64; 19], d: f64, s: f64, r: f64, g: i64) -> f64 {
    let hard_penalty = if g == 2 { w[15] } else { 1.0 };
    let easy_bonus = if g == 4 { w[16] } else { 1.0 };
    let growth = (w[8].exp())
        * (11.0 - d)
        * s.powf(-w[9])
        * ((w[10] * (1.0 - r)).exp() - 1.0)
        * hard_penalty
        * easy_bonus;
    (s * (1.0 + growth)).max(0.1)
}

fn forget_stability(w: &[f64; 19], d: f64, s: f64, r: f64) -> f64 {
    let s_forget =
        w[11] * d.powf(-w[12]) * ((s + 1.0).powf(w[13]) - 1.0) * (w[14] * (1.0 - r)).exp();
    // A lapse cannot make a card more stable than it already was.
    s_forget.clamp(0.1, s)
}

fn interval_from_stability(stability: f64, cfg: &SchedConfig) -> u32 {
    let days = (stability / FACTOR) * (cfg.desired_retention.powf(1.0 / DECAY) - 1.0);
    days.round().clamp(
        cfg.minimum_interval_days as f64,
        cfg.maximum_interval_days as f64,
    ) as u32
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx() -> SchedContext {
        SchedContext {
            today: 100,
            config: SchedConfig {
                algorithm: Algorithm::Fsrs,
                ..SchedConfig::default()
            },
        }
    }

    fn new_card() -> CardState {
        CardState::new(2500)
    }

    #[test]
    fn first_review_intervals_are_monotonic() {
        let s = FsrsScheduler;
        let c = ctx();
        let again = days(s.answer(&new_card(), Rating::Again, &c).interval);
        let hard = days(s.answer(&new_card(), Rating::Hard, &c).interval);
        let good = days(s.answer(&new_card(), Rating::Good, &c).interval);
        let easy = days(s.answer(&new_card(), Rating::Easy, &c).interval);
        assert!(again <= hard, "{again} <= {hard}");
        assert!(hard <= good, "{hard} <= {good}");
        assert!(good < easy, "{good} < {easy}");
    }

    #[test]
    fn first_review_sets_memory_state() {
        let s = FsrsScheduler;
        let o = s.answer(&new_card(), Rating::Good, &ctx());
        let d = o.next.difficulty.unwrap();
        assert!((1.0..=10.0).contains(&d));
        assert!(o.next.stability.unwrap() > 0.0);
        assert_eq!(o.next.phase, CardPhase::Review);
    }

    #[test]
    fn repeated_good_grows_stability_and_interval() {
        let s = FsrsScheduler;
        let c = ctx();
        let first = s.answer(&new_card(), Rating::Good, &c);
        // Simulate reviewing on the due day.
        let mut later = c.clone();
        later.today = c.today + days(first.interval) as i32;
        let second = s.answer(&first.next, Rating::Good, &later);
        assert!(second.next.stability.unwrap() > first.next.stability.unwrap());
        assert!(days(second.interval) > days(first.interval));
    }

    #[test]
    fn again_is_a_lapse_that_drops_stability() {
        let s = FsrsScheduler;
        let c = ctx();
        let learned = s.answer(&new_card(), Rating::Easy, &c).next;
        let mut later = c.clone();
        later.today = c.today + 10;
        let lapsed = s.answer(&learned, Rating::Again, &later);
        assert_eq!(lapsed.next.lapses, 1);
        assert!(lapsed.next.stability.unwrap() <= learned.stability.unwrap());
    }

    fn days(i: Interval) -> u32 {
        match i {
            Interval::Days(d) => d,
            Interval::Minutes(_) => 0,
        }
    }
}
